import java_cup.runtime.*;

/* Terminals (tokens returned by the scanner). */

terminal Integer NUMERO;
terminal         AC, CC, COMA;


/* Non terminals */

non terminal axioma;
non terminal String lista;
non terminal String elem;


/* Precedences */


/* The grammar */

axioma ::= AC lista:l CC            {: System.out.println("["+l+"]"); :}
         ;
lista  ::= lista:l COMA elem:val    {: RESULT = l+", "+val; :}
         | elem:val                 {: RESULT = val; :}
         |                          {: RESULT = "NULL"; :}
         ;
elem   ::= AC lista:l CC            {: RESULT = l; :}
         | NUMERO:n                 {: RESULT = n.toString(); :}
         ;