
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\053\000\002\002\003\000\002\002\004\000\002\003" +
    "\003\000\002\003\004\000\002\004\004\000\002\004\004" +
    "\000\002\004\007\000\002\011\002\000\002\004\006\000" +
    "\002\004\007\000\002\004\011\000\002\004\007\000\002" +
    "\004\011\000\002\004\013\000\002\007\004\000\002\007" +
    "\005\000\002\010\003\000\002\010\003\000\002\010\003" +
    "\000\002\010\003\000\002\010\005\000\002\005\005\000" +
    "\002\005\005\000\002\005\005\000\002\005\005\000\002" +
    "\005\004\000\002\005\005\000\002\005\003\000\002\005" +
    "\003\000\002\005\003\000\002\005\003\000\002\005\003" +
    "\000\002\005\005\000\002\006\005\000\002\006\005\000" +
    "\002\006\005\000\002\006\005\000\002\006\005\000\002" +
    "\006\005\000\002\006\004\000\002\006\005\000\002\006" +
    "\005\000\002\006\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\144\000\044\005\004\012\020\014\015\033\026\034" +
    "\017\035\021\036\014\040\030\041\011\042\025\043\013" +
    "\044\023\045\006\046\027\047\031\050\007\051\022\001" +
    "\002\000\020\005\004\012\020\045\006\046\027\047\031" +
    "\050\007\051\022\001\002\000\046\002\001\005\004\012" +
    "\020\014\015\033\026\034\017\035\021\036\014\040\030" +
    "\041\011\042\025\043\013\044\023\045\006\046\027\047" +
    "\031\050\007\051\022\001\002\000\040\004\uffe2\005\uffe2" +
    "\006\uffe2\007\uffe2\011\144\013\uffe2\021\uffe2\022\uffe2\023" +
    "\uffe2\024\uffe2\025\uffe2\026\uffe2\027\uffe2\030\uffe2\031\uffe2" +
    "\001\002\000\036\004\uffe4\005\uffe4\006\uffe4\007\uffe4\013" +
    "\uffe4\021\uffe4\022\uffe4\023\uffe4\024\uffe4\025\uffe4\026\uffe4" +
    "\027\uffe4\030\uffe4\031\uffe4\001\002\000\006\016\142\045" +
    "\141\001\002\000\006\016\ufff1\045\ufff1\001\002\000\006" +
    "\020\136\021\137\001\002\000\006\016\uffef\045\uffef\001" +
    "\002\000\004\012\132\001\002\000\044\005\ufffa\012\ufffa" +
    "\014\ufffa\033\ufffa\034\ufffa\035\ufffa\036\ufffa\040\ufffa\041" +
    "\ufffa\042\ufffa\043\ufffa\044\ufffa\045\ufffa\046\ufffa\047\ufffa" +
    "\050\ufffa\051\ufffa\001\002\000\014\004\036\005\037\006" +
    "\041\007\040\021\125\001\002\000\004\012\117\001\002" +
    "\000\020\005\004\012\020\045\006\046\027\047\031\050" +
    "\007\051\022\001\002\000\044\005\004\012\020\014\015" +
    "\033\026\034\017\035\021\036\014\040\030\041\011\042" +
    "\025\043\013\044\023\045\006\046\027\047\031\050\007" +
    "\051\022\001\002\000\036\004\uffe3\005\uffe3\006\uffe3\007" +
    "\uffe3\013\uffe3\021\uffe3\022\uffe3\023\uffe3\024\uffe3\025\uffe3" +
    "\026\uffe3\027\uffe3\030\uffe3\031\uffe3\001\002\000\006\016" +
    "\uffee\045\uffee\001\002\000\050\002\uffff\005\uffff\012\uffff" +
    "\014\uffff\015\uffff\033\uffff\034\uffff\035\uffff\036\uffff\040" +
    "\uffff\041\uffff\042\uffff\043\uffff\044\uffff\045\uffff\046\uffff" +
    "\047\uffff\050\uffff\051\uffff\001\002\000\006\016\ufff0\045" +
    "\ufff0\001\002\000\004\012\104\001\002\000\036\004\uffe6" +
    "\005\uffe6\006\uffe6\007\uffe6\013\uffe6\021\uffe6\022\uffe6\023" +
    "\uffe6\024\uffe6\025\uffe6\026\uffe6\027\uffe6\030\uffe6\031\uffe6" +
    "\001\002\000\004\012\034\001\002\000\036\004\uffe5\005" +
    "\uffe5\006\uffe5\007\uffe5\013\uffe5\021\uffe5\022\uffe5\023\uffe5" +
    "\024\uffe5\025\uffe5\026\uffe5\027\uffe5\030\uffe5\031\uffe5\001" +
    "\002\000\004\002\033\001\002\000\004\002\000\001\002" +
    "\000\020\005\004\012\020\045\006\046\027\047\031\050" +
    "\007\051\022\001\002\000\014\004\036\005\037\006\041" +
    "\007\040\021\042\001\002\000\020\005\004\012\020\045" +
    "\006\046\027\047\031\050\007\051\022\001\002\000\020" +
    "\005\004\012\020\045\006\046\027\047\031\050\007\051" +
    "\022\001\002\000\020\005\004\012\020\045\006\046\027" +
    "\047\031\050\007\051\022\001\002\000\020\005\004\012" +
    "\020\045\006\046\027\047\031\050\007\051\022\001\002" +
    "\000\022\005\004\012\046\032\045\045\006\046\027\047" +
    "\031\050\007\051\022\001\002\000\026\004\036\005\037" +
    "\006\041\007\040\022\063\023\060\024\056\025\061\026" +
    "\064\027\062\001\002\000\010\021\074\030\051\031\052" +
    "\001\002\000\022\005\004\012\046\032\045\045\006\046" +
    "\027\047\031\050\007\051\022\001\002\000\022\005\004" +
    "\012\046\032\045\045\006\046\027\047\031\050\007\051" +
    "\022\001\002\000\030\004\036\005\037\006\041\007\040" +
    "\013\057\022\063\023\060\024\056\025\061\026\064\027" +
    "\062\001\002\000\010\013\053\030\051\031\052\001\002" +
    "\000\022\005\004\012\046\032\045\045\006\046\027\047" +
    "\031\050\007\051\022\001\002\000\022\005\004\012\046" +
    "\032\045\045\006\046\027\047\031\050\007\051\022\001" +
    "\002\000\012\013\uffd7\021\uffd7\030\uffd7\031\uffd7\001\002" +
    "\000\012\013\uffd8\021\uffd8\030\051\031\uffd8\001\002\000" +
    "\012\013\uffd9\021\uffd9\030\uffd9\031\uffd9\001\002\000\020" +
    "\005\004\012\020\045\006\046\027\047\031\050\007\051" +
    "\022\001\002\000\036\004\uffe7\005\uffe7\006\uffe7\007\uffe7" +
    "\013\uffe7\021\uffe7\022\uffe7\023\uffe7\024\uffe7\025\uffe7\026" +
    "\uffe7\027\uffe7\030\uffe7\031\uffe7\001\002\000\020\005\004" +
    "\012\020\045\006\046\027\047\031\050\007\051\022\001" +
    "\002\000\020\005\004\012\020\045\006\046\027\047\031" +
    "\050\007\051\022\001\002\000\020\005\004\012\020\045" +
    "\006\046\027\047\031\050\007\051\022\001\002\000\020" +
    "\005\004\012\020\045\006\046\027\047\031\050\007\051" +
    "\022\001\002\000\020\005\004\012\020\045\006\046\027" +
    "\047\031\050\007\051\022\001\002\000\022\004\036\005" +
    "\037\006\041\007\040\013\uffdd\021\uffdd\030\uffdd\031\uffdd" +
    "\001\002\000\022\004\036\005\037\006\041\007\040\013" +
    "\uffdc\021\uffdc\030\uffdc\031\uffdc\001\002\000\022\004\036" +
    "\005\037\006\041\007\040\013\uffdb\021\uffdb\030\uffdb\031" +
    "\uffdb\001\002\000\022\004\036\005\037\006\041\007\040" +
    "\013\uffdf\021\uffdf\030\uffdf\031\uffdf\001\002\000\022\004" +
    "\036\005\037\006\041\007\040\013\uffde\021\uffde\030\uffde" +
    "\031\uffde\001\002\000\022\004\036\005\037\006\041\007" +
    "\040\013\uffe0\021\uffe0\030\uffe0\031\uffe0\001\002\000\012" +
    "\013\uffda\021\uffda\030\uffda\031\uffda\001\002\000\020\005" +
    "\004\012\020\045\006\046\027\047\031\050\007\051\022" +
    "\001\002\000\014\004\036\005\037\006\041\007\040\013" +
    "\076\001\002\000\044\005\004\012\020\014\015\033\026" +
    "\034\017\035\021\036\014\040\030\041\011\042\025\043" +
    "\013\044\023\045\006\046\027\047\031\050\007\051\022" +
    "\001\002\000\052\002\ufff4\005\ufff4\012\ufff4\014\ufff4\015" +
    "\ufff4\033\ufff4\034\ufff4\035\ufff4\036\ufff4\037\ufff4\040\ufff4" +
    "\041\ufff4\042\ufff4\043\ufff4\044\ufff4\045\ufff4\046\ufff4\047" +
    "\ufff4\050\ufff4\051\ufff4\001\002\000\036\004\uffea\005\uffea" +
    "\006\uffea\007\uffea\013\uffea\021\uffea\022\uffea\023\uffea\024" +
    "\uffea\025\uffea\026\uffea\027\uffea\030\uffea\031\uffea\001\002" +
    "\000\036\004\uffe9\005\uffe9\006\uffe9\007\uffe9\013\uffe9\021" +
    "\uffe9\022\uffe9\023\uffe9\024\uffe9\025\uffe9\026\uffe9\027\uffe9" +
    "\030\uffe9\031\uffe9\001\002\000\036\004\uffeb\005\uffeb\006" +
    "\041\007\040\013\uffeb\021\uffeb\022\uffeb\023\uffeb\024\uffeb" +
    "\025\uffeb\026\uffeb\027\uffeb\030\uffeb\031\uffeb\001\002\000" +
    "\036\004\uffec\005\uffec\006\041\007\040\013\uffec\021\uffec" +
    "\022\uffec\023\uffec\024\uffec\025\uffec\026\uffec\027\uffec\030" +
    "\uffec\031\uffec\001\002\000\020\005\004\012\020\045\006" +
    "\046\027\047\031\050\007\051\022\001\002\000\014\004" +
    "\036\005\037\006\041\007\040\013\106\001\002\000\004" +
    "\021\107\001\002\000\052\002\ufffb\005\ufffb\012\ufffb\014" +
    "\ufffb\015\ufffb\033\ufffb\034\ufffb\035\ufffb\036\ufffb\037\ufffb" +
    "\040\ufffb\041\ufffb\042\ufffb\043\ufffb\044\ufffb\045\ufffb\046" +
    "\ufffb\047\ufffb\050\ufffb\051\ufffb\001\002\000\004\036\111" +
    "\001\002\000\004\012\112\001\002\000\022\005\004\012" +
    "\046\032\045\045\006\046\027\047\031\050\007\051\022" +
    "\001\002\000\010\013\114\030\051\031\052\001\002\000" +
    "\004\021\115\001\002\000\052\002\ufff5\005\ufff5\012\ufff5" +
    "\014\ufff5\015\ufff5\033\ufff5\034\ufff5\035\ufff5\036\ufff5\037" +
    "\ufff5\040\ufff5\041\ufff5\042\ufff5\043\ufff5\044\ufff5\045\ufff5" +
    "\046\ufff5\047\ufff5\050\ufff5\051\ufff5\001\002\000\014\004" +
    "\036\005\037\006\041\007\040\013\057\001\002\000\022" +
    "\005\004\012\046\032\045\045\006\046\027\047\031\050" +
    "\007\051\022\001\002\000\010\013\121\030\051\031\052" +
    "\001\002\000\044\005\004\012\020\014\015\033\026\034" +
    "\017\035\021\036\014\040\030\041\011\042\025\043\013" +
    "\044\023\045\006\046\027\047\031\050\007\051\022\001" +
    "\002\000\052\002\ufff8\005\ufff8\012\ufff8\014\ufff8\015\ufff8" +
    "\033\ufff8\034\ufff8\035\ufff8\036\ufff8\037\123\040\ufff8\041" +
    "\ufff8\042\ufff8\043\ufff8\044\ufff8\045\ufff8\046\ufff8\047\ufff8" +
    "\050\ufff8\051\ufff8\001\002\000\044\005\004\012\020\014" +
    "\015\033\026\034\017\035\021\036\014\040\030\041\011" +
    "\042\025\043\013\044\023\045\006\046\027\047\031\050" +
    "\007\051\022\001\002\000\052\002\ufff7\005\ufff7\012\ufff7" +
    "\014\ufff7\015\ufff7\033\ufff7\034\ufff7\035\ufff7\036\ufff7\037" +
    "\ufff7\040\ufff7\041\ufff7\042\ufff7\043\ufff7\044\ufff7\045\ufff7" +
    "\046\ufff7\047\ufff7\050\ufff7\051\ufff7\001\002\000\052\002" +
    "\ufffd\005\ufffd\012\ufffd\014\ufffd\015\ufffd\033\ufffd\034\ufffd" +
    "\035\ufffd\036\ufffd\037\ufffd\040\ufffd\041\ufffd\042\ufffd\043" +
    "\ufffd\044\ufffd\045\ufffd\046\ufffd\047\ufffd\050\ufffd\051\ufffd" +
    "\001\002\000\044\005\004\012\020\014\015\033\026\034" +
    "\017\035\021\036\014\040\030\041\011\042\025\043\013" +
    "\044\023\045\006\046\027\047\031\050\007\051\022\001" +
    "\002\000\046\005\004\012\020\014\015\015\130\033\026" +
    "\034\017\035\021\036\014\040\030\041\011\042\025\043" +
    "\013\044\023\045\006\046\027\047\031\050\007\051\022" +
    "\001\002\000\052\002\ufff9\005\ufff9\012\ufff9\014\ufff9\015" +
    "\ufff9\033\ufff9\034\ufff9\035\ufff9\036\ufff9\037\ufff9\040\ufff9" +
    "\041\ufff9\042\ufff9\043\ufff9\044\ufff9\045\ufff9\046\ufff9\047" +
    "\ufff9\050\ufff9\051\ufff9\001\002\000\050\002\ufffe\005\ufffe" +
    "\012\ufffe\014\ufffe\015\ufffe\033\ufffe\034\ufffe\035\ufffe\036" +
    "\ufffe\040\ufffe\041\ufffe\042\ufffe\043\ufffe\044\ufffe\045\ufffe" +
    "\046\ufffe\047\ufffe\050\ufffe\051\ufffe\001\002\000\022\005" +
    "\004\012\046\032\045\045\006\046\027\047\031\050\007" +
    "\051\022\001\002\000\010\013\134\030\051\031\052\001" +
    "\002\000\044\005\004\012\020\014\015\033\026\034\017" +
    "\035\021\036\014\040\030\041\011\042\025\043\013\044" +
    "\023\045\006\046\027\047\031\050\007\051\022\001\002" +
    "\000\052\002\ufff6\005\ufff6\012\ufff6\014\ufff6\015\ufff6\033" +
    "\ufff6\034\ufff6\035\ufff6\036\ufff6\037\ufff6\040\ufff6\041\ufff6" +
    "\042\ufff6\043\ufff6\044\ufff6\045\ufff6\046\ufff6\047\ufff6\050" +
    "\ufff6\051\ufff6\001\002\000\004\045\140\001\002\000\052" +
    "\002\ufffc\005\ufffc\012\ufffc\014\ufffc\015\ufffc\033\ufffc\034" +
    "\ufffc\035\ufffc\036\ufffc\037\ufffc\040\ufffc\041\ufffc\042\ufffc" +
    "\043\ufffc\044\ufffc\045\ufffc\046\ufffc\047\ufffc\050\ufffc\051" +
    "\ufffc\001\002\000\006\020\ufff2\021\ufff2\001\002\000\006" +
    "\020\ufff3\021\ufff3\001\002\000\004\017\143\001\002\000" +
    "\006\016\uffed\045\uffed\001\002\000\020\005\004\012\020" +
    "\045\006\046\027\047\031\050\007\051\022\001\002\000" +
    "\036\004\036\005\037\006\041\007\040\013\uffe1\021\uffe1" +
    "\022\uffe1\023\uffe1\024\uffe1\025\uffe1\026\uffe1\027\uffe1\030" +
    "\uffe1\031\uffe1\001\002\000\036\004\uffe8\005\uffe8\006\uffe8" +
    "\007\uffe8\013\uffe8\021\uffe8\022\uffe8\023\uffe8\024\uffe8\025" +
    "\uffe8\026\uffe8\027\uffe8\030\uffe8\031\uffe8\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\144\000\016\002\031\003\004\004\023\005\015\007" +
    "\011\010\007\001\001\000\004\005\145\001\001\000\012" +
    "\004\130\005\015\007\011\010\007\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\011\125\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\005\115\001\001\000\012\004\107\005\015\007" +
    "\011\010\007\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\005\034\001\001\000" +
    "\002\001\001\000\004\005\102\001\001\000\004\005\101" +
    "\001\001\000\004\005\100\001\001\000\004\005\077\001" +
    "\001\000\006\005\042\006\043\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\005\042\006\072\001\001\000" +
    "\006\005\046\006\047\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\005\042\006\054\001\001\000\006\005" +
    "\042\006\053\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\005\071\001\001\000\002\001" +
    "\001\000\004\005\070\001\001\000\004\005\067\001\001" +
    "\000\004\005\066\001\001\000\004\005\065\001\001\000" +
    "\004\005\064\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\005\074\001\001" +
    "\000\002\001\001\000\012\004\076\005\015\007\011\010" +
    "\007\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\005" +
    "\104\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\005" +
    "\042\006\112\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\005\042\006" +
    "\117\001\001\000\002\001\001\000\012\004\121\005\015" +
    "\007\011\010\007\001\001\000\002\001\001\000\012\004" +
    "\123\005\015\007\011\010\007\001\001\000\002\001\001" +
    "\000\002\001\001\000\014\003\126\004\023\005\015\007" +
    "\011\010\007\001\001\000\012\004\130\005\015\007\011" +
    "\010\007\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\005\042\006\132\001\001\000\002\001\001\000\012" +
    "\004\134\005\015\007\011\010\007\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\005\144\001\001\000\002\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // axioma ::= listaSentencias 
            {
              Object RESULT =null;
		int lsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST ls = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ls.gc(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("axioma",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= axioma EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // listaSentencias ::= sentencia 
            {
              AST RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AST(null, s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaSentencias",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // listaSentencias ::= listaSentencias sentencia 
            {
              AST RESULT =null;
		int lsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AST ls = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AST(ls, s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaSentencias",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // sentencia ::= expresion PYC 
            {
              AST RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		EXPRESION e = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // sentencia ::= declarVariable PYC 
            {
              AST RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		DECLARVAR d = (DECLARVAR)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = d; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // sentencia ::= PRINT AP expresion CP PYC 
            {
              AST RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new PRINT(e, null); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // NT$0 ::= 
            {
              AST RESULT =null;
 TablaSimbolos.nuevaTabla(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // sentencia ::= ALL NT$0 listaSentencias CLL 
            {
              AST RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (AST) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int lsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AST ls = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
                                                           TablaSimbolos.cierraTabla();
                                                           RESULT = ls; 
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // sentencia ::= IF AP condicion CP sentencia 
            {
              AST RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		CONDICION c = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new IF(c, s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // sentencia ::= IF AP condicion CP sentencia ELSE sentencia 
            {
              AST RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		CONDICION c = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int s1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int s1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST s1 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int s2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int s2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s2 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                                                            IF p1 = new IF(c, s1); 
                                                            RESULT = new IFELSE(p1, s2); 
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // sentencia ::= WHILE AP condicion CP sentencia 
            {
              AST RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		CONDICION c = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new WHILE(c,s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // sentencia ::= DO sentencia WHILE AP condicion CP PYC 
            {
              AST RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		CONDICION c = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 
                                                            RESULT = new DOWHILE(s, c); 
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // sentencia ::= FOR AP expresion PYC condicion PYC expresion CP sentencia 
            {
              AST RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		CONDICION c = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e2 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                                                            AST sentwhile = new AST(s, e2);
                                                            WHILE eqFor = new WHILE(c, sentwhile);
                                                            RESULT = new FOR(e1, eqFor);
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // declarVariable ::= tipo IDENT 
            {
              DECLARVAR RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		TIPO t = (TIPO)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                                                            if(TablaSimbolos.estaDefinida(id)){
                                                                Generador.error();
                                                            } else {
                                                                // COMENTARIO System.out.println("variable ind "+id+" acaba de declararse");
                                                                TablaSimbolos.insertar(t, id);
                                                            }
                                                            RESULT = new DECLARVAR(t, id);
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declarVariable",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // declarVariable ::= declarVariable COMA IDENT 
            {
              DECLARVAR RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		DECLARVAR d = (DECLARVAR)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                                                            if(TablaSimbolos.estaDefinida(id)){
                                                                Generador.error();
                                                            } else {
                                                                // COMENTARIO System.out.println("variable lst "+id+" acaba de declararse");
                                                                TablaSimbolos.insertar(d.getTipo(), id);
                                                            }
                                                            RESULT = new DECLARVAR(d.getTipo(), id);
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declarVariable",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // tipo ::= INT 
            {
              TIPO RESULT =null;
		 RESULT = new TIPO(TIPO.ENTERO); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // tipo ::= FLOAT 
            {
              TIPO RESULT =null;
		 RESULT = new TIPO(TIPO.REAL); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // tipo ::= CHAR 
            {
              TIPO RESULT =null;
		 RESULT = new TIPO(TIPO.CARACTER); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // tipo ::= STRING 
            {
              TIPO RESULT =null;
		 RESULT = new TIPO(TIPO.CADENA); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // tipo ::= tipo AC CC 
            {
              TIPO RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		TIPO t = (TIPO)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new TIPO(TIPO.VECTOR, t.getTipo()); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expresion ::= expresion MAS expresion 
            {
              EXPRESION RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e2 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new MAS(e1, e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expresion ::= expresion MENOS expresion 
            {
              EXPRESION RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e2 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new MENOS(e1, e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expresion ::= expresion POR expresion 
            {
              EXPRESION RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e2 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new POR(e1, e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expresion ::= expresion DIV expresion 
            {
              EXPRESION RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e2 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DIV(e1, e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expresion ::= MENOS expresion 
            {
              EXPRESION RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new MENOS(null, e); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expresion ::= AP expresion CP 
            {
              EXPRESION RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		EXPRESION e = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expresion ::= ENTERO 
            {
              EXPRESION RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CTE(n, null, new TIPO(TIPO.ENTERO)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expresion ::= REAL 
            {
              EXPRESION RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String r = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CTE(r, null, new TIPO(TIPO.REAL)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expresion ::= CADENA 
            {
              EXPRESION RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CTE(s, null, new TIPO(TIPO.CADENA)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expresion ::= CARACTER 
            {
              EXPRESION RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CTE(c, null, new TIPO(TIPO.CARACTER)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expresion ::= IDENT 
            {
              EXPRESION RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                                                            TIPO tipo = TablaSimbolos.getTipo(id);
                                                            //Si no ha sido aun declarada emitimos error
                                                            if(tipo==null){
                                                                // COMENTARIO System.out.println("El tipo de la variable "+id+" es nulo");
                                                                Generador.error();
                                                            }
                                                            RESULT = new CTE(id, null, tipo); 
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expresion ::= IDENT IGUAL expresion 
            {
              EXPRESION RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  
                                                            TIPO tipo = TablaSimbolos.getTipo(id);
                                                            //Si no ha sido declarada emitimos error
                                                            if(tipo == null){
                                                                // COMENTARIO System.out.println("El tipo de la variable "+id+" es nulo (id = e)");
                                                                Generador.error();
                                                            }
                                                            //Si es declarada pero se le asigna un tipo correcto
                                                            //emitimos error
                                                            // COMENTARIO System.out.println("El tipo de la variable "+id+" es "+tipo.getTipo() );
                                                            // COMENTARIO System.out.println("El tipo de la expresion es "+" "+e.getTipo());
                                                            if(tipo.getTipo() != e.getTipo()){
                                                                
                                                                Generador.error();
                                                            }
                                                            RESULT = new ASIG(id, e); 
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // condicion ::= expresion IGUALDAD expresion 
            {
              CONDICION RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e2 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new IGUALDAD(e1,e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // condicion ::= expresion NOIGUALDAD expresion 
            {
              CONDICION RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new NOIGUALDAD(e1,e); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // condicion ::= expresion MENOR expresion 
            {
              CONDICION RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e2 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new MENOR(e1,e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // condicion ::= expresion MENOREQ expresion 
            {
              CONDICION RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new MENOREQ(e1,e); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // condicion ::= expresion MAYOR expresion 
            {
              CONDICION RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e2 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new MAYOR(e1,e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // condicion ::= expresion MAYOREQ expresion 
            {
              CONDICION RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new MAYOREQ(e1,e); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // condicion ::= NOT condicion 
            {
              CONDICION RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		CONDICION c = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new NOT(c,null); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // condicion ::= condicion AND condicion 
            {
              CONDICION RESULT =null;
		int c1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int c1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		CONDICION c1 = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int c2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int c2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		CONDICION c2 = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AND(c1, c2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // condicion ::= condicion OR condicion 
            {
              CONDICION RESULT =null;
		int c1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int c1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		CONDICION c1 = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int c2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int c2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		CONDICION c2 = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new OR(c1,c2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // condicion ::= AP condicion CP 
            {
              CONDICION RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		CONDICION c = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = c; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
