
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 19;
  public static final int MENOS = 3;
  public static final int MENOR = 14;
  public static final int IDENT = 28;
  public static final int ELSE = 26;
  public static final int CP = 9;
  public static final int MAYOREQ = 18;
  public static final int PYC = 12;
  public static final int OR = 20;
  public static final int IGUAL = 7;
  public static final int WHILE = 25;
  public static final int ALL = 10;
  public static final int NOT = 21;
  public static final int NOIGUALDAD = 16;
  public static final int CLL = 11;
  public static final int IF = 23;
  public static final int POR = 4;
  public static final int AP = 8;
  public static final int IGUALDAD = 15;
  public static final int DO = 24;
  public static final int MENOSUNARIO = 6;
  public static final int MAYOR = 13;
  public static final int EOF = 0;
  public static final int DIV = 5;
  public static final int PRINT = 22;
  public static final int error = 1;
  public static final int ENTERO = 29;
  public static final int MENOREQ = 17;
  public static final int FOR = 27;
  public static final int MAS = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "MENOSUNARIO",
  "IGUAL",
  "AP",
  "CP",
  "ALL",
  "CLL",
  "PYC",
  "MAYOR",
  "MENOR",
  "IGUALDAD",
  "NOIGUALDAD",
  "MENOREQ",
  "MAYOREQ",
  "AND",
  "OR",
  "NOT",
  "PRINT",
  "IF",
  "DO",
  "WHILE",
  "ELSE",
  "FOR",
  "IDENT",
  "ENTERO"
  };
}

