
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 15;
  public static final int AND = 26;
  public static final int MENOS = 12;
  public static final int LT = 20;
  public static final int NE = 17;
  public static final int IDENT = 29;
  public static final int CP = 5;
  public static final int PYC = 9;
  public static final int OR = 27;
  public static final int EOLN = 31;
  public static final int IN = 23;
  public static final int ALL = 2;
  public static final int NOT = 28;
  public static final int CLL = 3;
  public static final int IF = 25;
  public static final int GT = 21;
  public static final int CC = 7;
  public static final int LE = 18;
  public static final int POR = 13;
  public static final int AP = 4;
  public static final int COMA = 8;
  public static final int EOF = 0;
  public static final int DIV = 14;
  public static final int GE = 19;
  public static final int AC = 6;
  public static final int NUMERO = 30;
  public static final int PRINT = 24;
  public static final int error = 1;
  public static final int EQ = 16;
  public static final int FOR = 22;
  public static final int ASIG = 10;
  public static final int MAS = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ALL",
  "CLL",
  "AP",
  "CP",
  "AC",
  "CC",
  "COMA",
  "PYC",
  "ASIG",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "MOD",
  "EQ",
  "NE",
  "LE",
  "GE",
  "LT",
  "GT",
  "FOR",
  "IN",
  "PRINT",
  "IF",
  "AND",
  "OR",
  "NOT",
  "IDENT",
  "NUMERO",
  "EOLN"
  };
}

