
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\071\000\002\002\003\000\002\002\004\000\002\003" +
    "\003\000\002\003\004\000\002\004\004\000\002\004\004" +
    "\000\002\004\004\000\002\004\007\000\002\014\002\000" +
    "\002\004\006\000\002\004\007\000\002\004\011\000\002" +
    "\004\007\000\002\004\011\000\002\004\013\000\002\007" +
    "\004\000\002\007\006\000\002\007\007\000\002\007\005" +
    "\000\002\010\007\000\002\010\011\000\002\010\010\000" +
    "\002\010\012\000\002\011\003\000\002\011\003\000\002" +
    "\011\003\000\002\011\003\000\002\011\005\000\002\005" +
    "\005\000\002\005\005\000\002\005\005\000\002\005\005" +
    "\000\002\005\004\000\002\005\005\000\002\005\003\000" +
    "\002\005\003\000\002\005\003\000\002\005\003\000\002" +
    "\005\003\000\002\005\005\000\002\005\006\000\002\005" +
    "\010\000\002\005\005\000\002\005\002\000\002\013\005" +
    "\000\002\012\005\000\002\012\003\000\002\006\005\000" +
    "\002\006\005\000\002\006\005\000\002\006\005\000\002" +
    "\006\005\000\002\006\005\000\002\006\004\000\002\006" +
    "\005\000\002\006\005\000\002\006\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\202\000\054\004\uffd6\005\004\006\uffd6\007\uffd6\012" +
    "\021\014\015\021\uffd6\033\027\034\020\035\022\036\013" +
    "\040\031\041\011\042\026\043\014\044\024\045\006\046" +
    "\030\047\032\050\007\051\023\001\002\000\060\004\uffd6" +
    "\005\004\006\uffd6\007\uffd6\012\021\013\uffd6\015\uffd6\017" +
    "\uffd6\020\uffd6\021\uffd6\022\uffd6\023\uffd6\024\uffd6\025\uffd6" +
    "\026\uffd6\027\uffd6\030\uffd6\031\uffd6\045\006\046\030\047" +
    "\032\050\007\051\023\001\002\000\056\002\001\004\uffd6" +
    "\005\004\006\uffd6\007\uffd6\012\021\014\015\021\uffd6\033" +
    "\027\034\020\035\022\036\013\040\031\041\011\042\026" +
    "\043\014\044\024\045\006\046\030\047\032\050\007\051" +
    "\023\001\002\000\050\004\uffdb\005\uffdb\006\uffdb\007\uffdb" +
    "\011\174\013\uffdb\015\uffdb\016\175\017\uffdb\020\uffdb\021" +
    "\uffdb\022\uffdb\023\uffdb\024\uffdb\025\uffdb\026\uffdb\027\uffdb" +
    "\030\uffdb\031\uffdb\001\002\000\044\004\uffdd\005\uffdd\006" +
    "\uffdd\007\uffdd\013\uffdd\015\uffdd\017\uffdd\020\uffdd\021\uffdd" +
    "\022\uffdd\023\uffdd\024\uffdd\025\uffdd\026\uffdd\027\uffdd\030" +
    "\uffdd\031\uffdd\001\002\000\006\016\163\045\162\001\002" +
    "\000\006\016\uffea\045\uffea\001\002\000\006\020\155\021" +
    "\156\001\002\000\004\012\151\001\002\000\006\016\uffe8" +
    "\045\uffe8\001\002\000\054\004\ufff9\005\ufff9\006\ufff9\007" +
    "\ufff9\012\ufff9\014\ufff9\021\ufff9\033\ufff9\034\ufff9\035\ufff9" +
    "\036\ufff9\040\ufff9\041\ufff9\042\ufff9\043\ufff9\044\ufff9\045" +
    "\ufff9\046\ufff9\047\ufff9\050\ufff9\051\ufff9\001\002\000\014" +
    "\004\037\005\040\006\042\007\041\021\144\001\002\000" +
    "\006\020\126\021\127\001\002\000\004\012\120\001\002" +
    "\000\030\004\uffd6\005\004\006\uffd6\007\uffd6\012\021\013" +
    "\uffd6\045\006\046\030\047\032\050\007\051\023\001\002" +
    "\000\054\004\uffd6\005\004\006\uffd6\007\uffd6\012\021\014" +
    "\015\021\uffd6\033\027\034\020\035\022\036\013\040\031" +
    "\041\011\042\026\043\014\044\024\045\006\046\030\047" +
    "\032\050\007\051\023\001\002\000\044\004\uffdc\005\uffdc" +
    "\006\uffdc\007\uffdc\013\uffdc\015\uffdc\017\uffdc\020\uffdc\021" +
    "\uffdc\022\uffdc\023\uffdc\024\uffdc\025\uffdc\026\uffdc\027\uffdc" +
    "\030\uffdc\031\uffdc\001\002\000\006\016\uffe7\045\uffe7\001" +
    "\002\000\060\002\uffff\004\uffff\005\uffff\006\uffff\007\uffff" +
    "\012\uffff\014\uffff\015\uffff\021\uffff\033\uffff\034\uffff\035" +
    "\uffff\036\uffff\040\uffff\041\uffff\042\uffff\043\uffff\044\uffff" +
    "\045\uffff\046\uffff\047\uffff\050\uffff\051\uffff\001\002\000" +
    "\006\016\uffe9\045\uffe9\001\002\000\004\012\105\001\002" +
    "\000\044\004\uffdf\005\uffdf\006\uffdf\007\uffdf\013\uffdf\015" +
    "\uffdf\017\uffdf\020\uffdf\021\uffdf\022\uffdf\023\uffdf\024\uffdf" +
    "\025\uffdf\026\uffdf\027\uffdf\030\uffdf\031\uffdf\001\002\000" +
    "\004\012\035\001\002\000\044\004\uffde\005\uffde\006\uffde" +
    "\007\uffde\013\uffde\015\uffde\017\uffde\020\uffde\021\uffde\022" +
    "\uffde\023\uffde\024\uffde\025\uffde\026\uffde\027\uffde\030\uffde" +
    "\031\uffde\001\002\000\004\002\034\001\002\000\004\002" +
    "\000\001\002\000\030\004\uffd6\005\004\006\uffd6\007\uffd6" +
    "\012\021\021\uffd6\045\006\046\030\047\032\050\007\051" +
    "\023\001\002\000\014\004\037\005\040\006\042\007\041" +
    "\021\043\001\002\000\060\004\uffd6\005\004\006\uffd6\007" +
    "\uffd6\012\021\013\uffd6\015\uffd6\017\uffd6\020\uffd6\021\uffd6" +
    "\022\uffd6\023\uffd6\024\uffd6\025\uffd6\026\uffd6\027\uffd6\030" +
    "\uffd6\031\uffd6\045\006\046\030\047\032\050\007\051\023" +
    "\001\002\000\060\004\uffd6\005\004\006\uffd6\007\uffd6\012" +
    "\021\013\uffd6\015\uffd6\017\uffd6\020\uffd6\021\uffd6\022\uffd6" +
    "\023\uffd6\024\uffd6\025\uffd6\026\uffd6\027\uffd6\030\uffd6\031" +
    "\uffd6\045\006\046\030\047\032\050\007\051\023\001\002" +
    "\000\060\004\uffd6\005\004\006\uffd6\007\uffd6\012\021\013" +
    "\uffd6\015\uffd6\017\uffd6\020\uffd6\021\uffd6\022\uffd6\023\uffd6" +
    "\024\uffd6\025\uffd6\026\uffd6\027\uffd6\030\uffd6\031\uffd6\045" +
    "\006\046\030\047\032\050\007\051\023\001\002\000\060" +
    "\004\uffd6\005\004\006\uffd6\007\uffd6\012\021\013\uffd6\015" +
    "\uffd6\017\uffd6\020\uffd6\021\uffd6\022\uffd6\023\uffd6\024\uffd6" +
    "\025\uffd6\026\uffd6\027\uffd6\030\uffd6\031\uffd6\045\006\046" +
    "\030\047\032\050\007\051\023\001\002\000\044\004\uffd6" +
    "\005\004\006\uffd6\007\uffd6\012\047\022\uffd6\023\uffd6\024" +
    "\uffd6\025\uffd6\026\uffd6\027\uffd6\032\046\045\006\046\030" +
    "\047\032\050\007\051\023\001\002\000\026\004\037\005" +
    "\040\006\042\007\041\022\064\023\060\024\057\025\062" +
    "\026\065\027\063\001\002\000\010\021\075\030\052\031" +
    "\053\001\002\000\044\004\uffd6\005\004\006\uffd6\007\uffd6" +
    "\012\047\022\uffd6\023\uffd6\024\uffd6\025\uffd6\026\uffd6\027" +
    "\uffd6\032\046\045\006\046\030\047\032\050\007\051\023" +
    "\001\002\000\046\004\uffd6\005\004\006\uffd6\007\uffd6\012" +
    "\047\013\uffd6\022\uffd6\023\uffd6\024\uffd6\025\uffd6\026\uffd6" +
    "\027\uffd6\032\046\045\006\046\030\047\032\050\007\051" +
    "\023\001\002\000\030\004\037\005\040\006\042\007\041" +
    "\013\061\022\064\023\060\024\057\025\062\026\065\027" +
    "\063\001\002\000\010\013\054\030\052\031\053\001\002" +
    "\000\044\004\uffd6\005\004\006\uffd6\007\uffd6\012\047\022" +
    "\uffd6\023\uffd6\024\uffd6\025\uffd6\026\uffd6\027\uffd6\032\046" +
    "\045\006\046\030\047\032\050\007\051\023\001\002\000" +
    "\044\004\uffd6\005\004\006\uffd6\007\uffd6\012\047\022\uffd6" +
    "\023\uffd6\024\uffd6\025\uffd6\026\uffd6\027\uffd6\032\046\045" +
    "\006\046\030\047\032\050\007\051\023\001\002\000\012" +
    "\013\uffc9\021\uffc9\030\uffc9\031\uffc9\001\002\000\012\013" +
    "\uffca\021\uffca\030\052\031\uffca\001\002\000\012\013\uffcb" +
    "\021\uffcb\030\uffcb\031\uffcb\001\002\000\036\004\uffd6\005" +
    "\004\006\uffd6\007\uffd6\012\021\013\uffd6\021\uffd6\030\uffd6" +
    "\031\uffd6\045\006\046\030\047\032\050\007\051\023\001" +
    "\002\000\036\004\uffd6\005\004\006\uffd6\007\uffd6\012\021" +
    "\013\uffd6\021\uffd6\030\uffd6\031\uffd6\045\006\046\030\047" +
    "\032\050\007\051\023\001\002\000\044\004\uffe0\005\uffe0" +
    "\006\uffe0\007\uffe0\013\uffe0\015\uffe0\017\uffe0\020\uffe0\021" +
    "\uffe0\022\uffe0\023\uffe0\024\uffe0\025\uffe0\026\uffe0\027\uffe0" +
    "\030\uffe0\031\uffe0\001\002\000\036\004\uffd6\005\004\006" +
    "\uffd6\007\uffd6\012\021\013\uffd6\021\uffd6\030\uffd6\031\uffd6" +
    "\045\006\046\030\047\032\050\007\051\023\001\002\000" +
    "\036\004\uffd6\005\004\006\uffd6\007\uffd6\012\021\013\uffd6" +
    "\021\uffd6\030\uffd6\031\uffd6\045\006\046\030\047\032\050" +
    "\007\051\023\001\002\000\036\004\uffd6\005\004\006\uffd6" +
    "\007\uffd6\012\021\013\uffd6\021\uffd6\030\uffd6\031\uffd6\045" +
    "\006\046\030\047\032\050\007\051\023\001\002\000\036" +
    "\004\uffd6\005\004\006\uffd6\007\uffd6\012\021\013\uffd6\021" +
    "\uffd6\030\uffd6\031\uffd6\045\006\046\030\047\032\050\007" +
    "\051\023\001\002\000\022\004\037\005\040\006\042\007" +
    "\041\013\uffcf\021\uffcf\030\uffcf\031\uffcf\001\002\000\022" +
    "\004\037\005\040\006\042\007\041\013\uffce\021\uffce\030" +
    "\uffce\031\uffce\001\002\000\022\004\037\005\040\006\042" +
    "\007\041\013\uffcd\021\uffcd\030\uffcd\031\uffcd\001\002\000" +
    "\022\004\037\005\040\006\042\007\041\013\uffd1\021\uffd1" +
    "\030\uffd1\031\uffd1\001\002\000\022\004\037\005\040\006" +
    "\042\007\041\013\uffd0\021\uffd0\030\uffd0\031\uffd0\001\002" +
    "\000\022\004\037\005\040\006\042\007\041\013\uffd2\021" +
    "\uffd2\030\uffd2\031\uffd2\001\002\000\012\013\uffcc\021\uffcc" +
    "\030\uffcc\031\uffcc\001\002\000\030\004\uffd6\005\004\006" +
    "\uffd6\007\uffd6\012\021\013\uffd6\045\006\046\030\047\032" +
    "\050\007\051\023\001\002\000\014\004\037\005\040\006" +
    "\042\007\041\013\077\001\002\000\054\004\uffd6\005\004" +
    "\006\uffd6\007\uffd6\012\021\014\015\021\uffd6\033\027\034" +
    "\020\035\022\036\013\040\031\041\011\042\026\043\014" +
    "\044\024\045\006\046\030\047\032\050\007\051\023\001" +
    "\002\000\062\002\ufff3\004\ufff3\005\ufff3\006\ufff3\007\ufff3" +
    "\012\ufff3\014\ufff3\015\ufff3\021\ufff3\033\ufff3\034\ufff3\035" +
    "\ufff3\036\ufff3\037\ufff3\040\ufff3\041\ufff3\042\ufff3\043\ufff3" +
    "\044\ufff3\045\ufff3\046\ufff3\047\ufff3\050\ufff3\051\ufff3\001" +
    "\002\000\044\004\uffe3\005\uffe3\006\uffe3\007\uffe3\013\uffe3" +
    "\015\uffe3\017\uffe3\020\uffe3\021\uffe3\022\uffe3\023\uffe3\024" +
    "\uffe3\025\uffe3\026\uffe3\027\uffe3\030\uffe3\031\uffe3\001\002" +
    "\000\044\004\uffe2\005\uffe2\006\uffe2\007\uffe2\013\uffe2\015" +
    "\uffe2\017\uffe2\020\uffe2\021\uffe2\022\uffe2\023\uffe2\024\uffe2" +
    "\025\uffe2\026\uffe2\027\uffe2\030\uffe2\031\uffe2\001\002\000" +
    "\044\004\uffe4\005\uffe4\006\042\007\041\013\uffe4\015\uffe4" +
    "\017\uffe4\020\uffe4\021\uffe4\022\uffe4\023\uffe4\024\uffe4\025" +
    "\uffe4\026\uffe4\027\uffe4\030\uffe4\031\uffe4\001\002\000\044" +
    "\004\uffe5\005\uffe5\006\042\007\041\013\uffe5\015\uffe5\017" +
    "\uffe5\020\uffe5\021\uffe5\022\uffe5\023\uffe5\024\uffe5\025\uffe5" +
    "\026\uffe5\027\uffe5\030\uffe5\031\uffe5\001\002\000\030\004" +
    "\uffd6\005\004\006\uffd6\007\uffd6\012\021\013\uffd6\045\006" +
    "\046\030\047\032\050\007\051\023\001\002\000\014\004" +
    "\037\005\040\006\042\007\041\013\107\001\002\000\004" +
    "\021\110\001\002\000\062\002\ufffa\004\ufffa\005\ufffa\006" +
    "\ufffa\007\ufffa\012\ufffa\014\ufffa\015\ufffa\021\ufffa\033\ufffa" +
    "\034\ufffa\035\ufffa\036\ufffa\037\ufffa\040\ufffa\041\ufffa\042" +
    "\ufffa\043\ufffa\044\ufffa\045\ufffa\046\ufffa\047\ufffa\050\ufffa" +
    "\051\ufffa\001\002\000\004\036\112\001\002\000\004\012" +
    "\113\001\002\000\044\004\uffd6\005\004\006\uffd6\007\uffd6" +
    "\012\047\022\uffd6\023\uffd6\024\uffd6\025\uffd6\026\uffd6\027" +
    "\uffd6\032\046\045\006\046\030\047\032\050\007\051\023" +
    "\001\002\000\010\013\115\030\052\031\053\001\002\000" +
    "\004\021\116\001\002\000\062\002\ufff4\004\ufff4\005\ufff4" +
    "\006\ufff4\007\ufff4\012\ufff4\014\ufff4\015\ufff4\021\ufff4\033" +
    "\ufff4\034\ufff4\035\ufff4\036\ufff4\037\ufff4\040\ufff4\041\ufff4" +
    "\042\ufff4\043\ufff4\044\ufff4\045\ufff4\046\ufff4\047\ufff4\050" +
    "\ufff4\051\ufff4\001\002\000\014\004\037\005\040\006\042" +
    "\007\041\013\061\001\002\000\044\004\uffd6\005\004\006" +
    "\uffd6\007\uffd6\012\047\022\uffd6\023\uffd6\024\uffd6\025\uffd6" +
    "\026\uffd6\027\uffd6\032\046\045\006\046\030\047\032\050" +
    "\007\051\023\001\002\000\010\013\122\030\052\031\053" +
    "\001\002\000\054\004\uffd6\005\004\006\uffd6\007\uffd6\012" +
    "\021\014\015\021\uffd6\033\027\034\020\035\022\036\013" +
    "\040\031\041\011\042\026\043\014\044\024\045\006\046" +
    "\030\047\032\050\007\051\023\001\002\000\062\002\ufff7" +
    "\004\ufff7\005\ufff7\006\ufff7\007\ufff7\012\ufff7\014\ufff7\015" +
    "\ufff7\021\ufff7\033\ufff7\034\ufff7\035\ufff7\036\ufff7\037\124" +
    "\040\ufff7\041\ufff7\042\ufff7\043\ufff7\044\ufff7\045\ufff7\046" +
    "\ufff7\047\ufff7\050\ufff7\051\ufff7\001\002\000\054\004\uffd6" +
    "\005\004\006\uffd6\007\uffd6\012\021\014\015\021\uffd6\033" +
    "\027\034\020\035\022\036\013\040\031\041\011\042\026" +
    "\043\014\044\024\045\006\046\030\047\032\050\007\051" +
    "\023\001\002\000\062\002\ufff6\004\ufff6\005\ufff6\006\ufff6" +
    "\007\ufff6\012\ufff6\014\ufff6\015\ufff6\021\ufff6\033\ufff6\034" +
    "\ufff6\035\ufff6\036\ufff6\037\ufff6\040\ufff6\041\ufff6\042\ufff6" +
    "\043\ufff6\044\ufff6\045\ufff6\046\ufff6\047\ufff6\050\ufff6\051" +
    "\ufff6\001\002\000\004\045\130\001\002\000\062\002\ufffb" +
    "\004\ufffb\005\ufffb\006\ufffb\007\ufffb\012\ufffb\014\ufffb\015" +
    "\ufffb\021\ufffb\033\ufffb\034\ufffb\035\ufffb\036\ufffb\037\ufffb" +
    "\040\ufffb\041\ufffb\042\ufffb\043\ufffb\044\ufffb\045\ufffb\046" +
    "\ufffb\047\ufffb\050\ufffb\051\ufffb\001\002\000\004\016\131" +
    "\001\002\000\004\046\132\001\002\000\004\017\133\001" +
    "\002\000\010\011\134\020\uffec\021\uffec\001\002\000\004" +
    "\014\135\001\002\000\032\004\uffd6\005\004\006\uffd6\007" +
    "\uffd6\012\021\015\uffd6\020\uffd6\045\006\046\030\047\032" +
    "\050\007\051\023\001\002\000\006\020\uffeb\021\uffeb\001" +
    "\002\000\016\004\037\005\040\006\042\007\041\015\uffd3" +
    "\020\uffd3\001\002\000\006\015\142\020\141\001\002\000" +
    "\032\004\uffd6\005\004\006\uffd6\007\uffd6\012\021\015\uffd6" +
    "\020\uffd6\045\006\046\030\047\032\050\007\051\023\001" +
    "\002\000\044\004\uffd5\005\uffd5\006\uffd5\007\uffd5\013\uffd5" +
    "\015\uffd5\017\uffd5\020\uffd5\021\uffd5\022\uffd5\023\uffd5\024" +
    "\uffd5\025\uffd5\026\uffd5\027\uffd5\030\uffd5\031\uffd5\001\002" +
    "\000\016\004\037\005\040\006\042\007\041\015\uffd4\020" +
    "\uffd4\001\002\000\062\002\ufffd\004\ufffd\005\ufffd\006\ufffd" +
    "\007\ufffd\012\ufffd\014\ufffd\015\ufffd\021\ufffd\033\ufffd\034" +
    "\ufffd\035\ufffd\036\ufffd\037\ufffd\040\ufffd\041\ufffd\042\ufffd" +
    "\043\ufffd\044\ufffd\045\ufffd\046\ufffd\047\ufffd\050\ufffd\051" +
    "\ufffd\001\002\000\054\004\uffd6\005\004\006\uffd6\007\uffd6" +
    "\012\021\014\015\021\uffd6\033\027\034\020\035\022\036" +
    "\013\040\031\041\011\042\026\043\014\044\024\045\006" +
    "\046\030\047\032\050\007\051\023\001\002\000\056\004" +
    "\uffd6\005\004\006\uffd6\007\uffd6\012\021\014\015\015\147" +
    "\021\uffd6\033\027\034\020\035\022\036\013\040\031\041" +
    "\011\042\026\043\014\044\024\045\006\046\030\047\032" +
    "\050\007\051\023\001\002\000\062\002\ufff8\004\ufff8\005" +
    "\ufff8\006\ufff8\007\ufff8\012\ufff8\014\ufff8\015\ufff8\021\ufff8" +
    "\033\ufff8\034\ufff8\035\ufff8\036\ufff8\037\ufff8\040\ufff8\041" +
    "\ufff8\042\ufff8\043\ufff8\044\ufff8\045\ufff8\046\ufff8\047\ufff8" +
    "\050\ufff8\051\ufff8\001\002\000\060\002\ufffe\004\ufffe\005" +
    "\ufffe\006\ufffe\007\ufffe\012\ufffe\014\ufffe\015\ufffe\021\ufffe" +
    "\033\ufffe\034\ufffe\035\ufffe\036\ufffe\040\ufffe\041\ufffe\042" +
    "\ufffe\043\ufffe\044\ufffe\045\ufffe\046\ufffe\047\ufffe\050\ufffe" +
    "\051\ufffe\001\002\000\044\004\uffd6\005\004\006\uffd6\007" +
    "\uffd6\012\047\022\uffd6\023\uffd6\024\uffd6\025\uffd6\026\uffd6" +
    "\027\uffd6\032\046\045\006\046\030\047\032\050\007\051" +
    "\023\001\002\000\010\013\153\030\052\031\053\001\002" +
    "\000\054\004\uffd6\005\004\006\uffd6\007\uffd6\012\021\014" +
    "\015\021\uffd6\033\027\034\020\035\022\036\013\040\031" +
    "\041\011\042\026\043\014\044\024\045\006\046\030\047" +
    "\032\050\007\051\023\001\002\000\062\002\ufff5\004\ufff5" +
    "\005\ufff5\006\ufff5\007\ufff5\012\ufff5\014\ufff5\015\ufff5\021" +
    "\ufff5\033\ufff5\034\ufff5\035\ufff5\036\ufff5\037\ufff5\040\ufff5" +
    "\041\ufff5\042\ufff5\043\ufff5\044\ufff5\045\ufff5\046\ufff5\047" +
    "\ufff5\050\ufff5\051\ufff5\001\002\000\004\045\157\001\002" +
    "\000\062\002\ufffc\004\ufffc\005\ufffc\006\ufffc\007\ufffc\012" +
    "\ufffc\014\ufffc\015\ufffc\021\ufffc\033\ufffc\034\ufffc\035\ufffc" +
    "\036\ufffc\037\ufffc\040\ufffc\041\ufffc\042\ufffc\043\ufffc\044" +
    "\ufffc\045\ufffc\046\ufffc\047\ufffc\050\ufffc\051\ufffc\001\002" +
    "\000\010\011\160\020\uffef\021\uffef\001\002\000\032\004" +
    "\uffd6\005\004\006\uffd6\007\uffd6\012\021\020\uffd6\021\uffd6" +
    "\045\006\046\030\047\032\050\007\051\023\001\002\000" +
    "\016\004\037\005\040\006\042\007\041\020\ufff0\021\ufff0" +
    "\001\002\000\012\011\165\016\166\020\ufff2\021\ufff2\001" +
    "\002\000\004\017\164\001\002\000\006\016\uffe6\045\uffe6" +
    "\001\002\000\032\004\uffd6\005\004\006\uffd6\007\uffd6\012" +
    "\021\020\uffd6\021\uffd6\045\006\046\030\047\032\050\007" +
    "\051\023\001\002\000\004\046\167\001\002\000\004\017" +
    "\170\001\002\000\010\011\171\020\uffee\021\uffee\001\002" +
    "\000\004\014\135\001\002\000\006\020\uffed\021\uffed\001" +
    "\002\000\016\004\037\005\040\006\042\007\041\020\ufff1" +
    "\021\ufff1\001\002\000\062\004\uffd6\005\004\006\uffd6\007" +
    "\uffd6\012\021\013\uffd6\014\135\015\uffd6\017\uffd6\020\uffd6" +
    "\021\uffd6\022\uffd6\023\uffd6\024\uffd6\025\uffd6\026\uffd6\027" +
    "\uffd6\030\uffd6\031\uffd6\045\006\046\030\047\032\050\007" +
    "\051\023\001\002\000\030\004\uffd6\005\004\006\uffd6\007" +
    "\uffd6\012\021\017\uffd6\045\006\046\030\047\032\050\007" +
    "\051\023\001\002\000\014\004\037\005\040\006\042\007" +
    "\041\017\177\001\002\000\046\004\uffd9\005\uffd9\006\uffd9" +
    "\007\uffd9\011\200\013\uffd9\015\uffd9\017\uffd9\020\uffd9\021" +
    "\uffd9\022\uffd9\023\uffd9\024\uffd9\025\uffd9\026\uffd9\027\uffd9" +
    "\030\uffd9\031\uffd9\001\002\000\060\004\uffd6\005\004\006" +
    "\uffd6\007\uffd6\012\021\013\uffd6\015\uffd6\017\uffd6\020\uffd6" +
    "\021\uffd6\022\uffd6\023\uffd6\024\uffd6\025\uffd6\026\uffd6\027" +
    "\uffd6\030\uffd6\031\uffd6\045\006\046\030\047\032\050\007" +
    "\051\023\001\002\000\044\004\037\005\040\006\042\007" +
    "\041\013\uffd8\015\uffd8\017\uffd8\020\uffd8\021\uffd8\022\uffd8" +
    "\023\uffd8\024\uffd8\025\uffd8\026\uffd8\027\uffd8\030\uffd8\031" +
    "\uffd8\001\002\000\044\004\uffd7\005\uffd7\006\uffd7\007\uffd7" +
    "\013\uffd7\015\uffd7\017\uffd7\020\uffd7\021\uffd7\022\uffd7\023" +
    "\uffd7\024\uffd7\025\uffd7\026\uffd7\027\uffd7\030\uffd7\031\uffd7" +
    "\001\002\000\044\004\037\005\040\006\042\007\041\013" +
    "\uffda\015\uffda\017\uffda\020\uffda\021\uffda\022\uffda\023\uffda" +
    "\024\uffda\025\uffda\026\uffda\027\uffda\030\uffda\031\uffda\001" +
    "\002\000\044\004\uffe1\005\uffe1\006\uffe1\007\uffe1\013\uffe1" +
    "\015\uffe1\017\uffe1\020\uffe1\021\uffe1\022\uffe1\023\uffe1\024" +
    "\uffe1\025\uffe1\026\uffe1\027\uffe1\030\uffe1\031\uffe1\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\202\000\020\002\032\003\004\004\024\005\015\007" +
    "\011\010\016\011\007\001\001\000\004\005\203\001\001" +
    "\000\014\004\147\005\015\007\011\010\016\011\007\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\014\144\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\005\116\001" +
    "\001\000\014\004\110\005\015\007\011\010\016\011\007" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\005\035\001\001\000\002\001\001" +
    "\000\004\005\103\001\001\000\004\005\102\001\001\000" +
    "\004\005\101\001\001\000\004\005\100\001\001\000\006" +
    "\005\043\006\044\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\005\043\006\073\001\001\000\006\005\047" +
    "\006\050\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\005\043\006\055\001\001\000\006\005\043\006\054" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\005\072\001\001\000\004\005\071\001\001" +
    "\000\002\001\001\000\004\005\070\001\001\000\004\005" +
    "\067\001\001\000\004\005\066\001\001\000\004\005\065" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\005\075\001\001\000\002\001" +
    "\001\000\014\004\077\005\015\007\011\010\016\011\007" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\005\105" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\005\043" +
    "\006\113\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\005\043\006\120" +
    "\001\001\000\002\001\001\000\014\004\122\005\015\007" +
    "\011\010\016\011\007\001\001\000\002\001\001\000\014" +
    "\004\124\005\015\007\011\010\016\011\007\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\013\135\001\001\000\006\005\136\012\137" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\005\142\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\016\003\145\004\024\005" +
    "\015\007\011\010\016\011\007\001\001\000\014\004\147" +
    "\005\015\007\011\010\016\011\007\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\005\043\006\151\001\001" +
    "\000\002\001\001\000\014\004\153\005\015\007\011\010" +
    "\016\011\007\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\005\160\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\005\172\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\013\171" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\005" +
    "\202\013\201\001\001\000\004\005\175\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\005\200\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // axioma ::= listaSentencias 
            {
              Object RESULT =null;
		int lsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST ls = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ls.gc(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("axioma",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= axioma EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // listaSentencias ::= sentencia 
            {
              AST RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AST(null, s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaSentencias",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // listaSentencias ::= listaSentencias sentencia 
            {
              AST RESULT =null;
		int lsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AST ls = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AST(ls, s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaSentencias",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // sentencia ::= expresion PYC 
            {
              AST RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		EXPRESION e = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // sentencia ::= declarVariable PYC 
            {
              AST RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		DECLARVAR d = (DECLARVAR)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = d; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // sentencia ::= declarVector PYC 
            {
              AST RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		DECLARVEC d = (DECLARVEC)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = d; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // sentencia ::= PRINT AP expresion CP PYC 
            {
              AST RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new PRINT(e, null); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // NT$0 ::= 
            {
              AST RESULT =null;
 TablaSimbolos.nuevaTabla(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // sentencia ::= ALL NT$0 listaSentencias CLL 
            {
              AST RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (AST) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int lsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		AST ls = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
                                                           TablaSimbolos.cierraTabla();
                                                           RESULT = ls; 
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // sentencia ::= IF AP condicion CP sentencia 
            {
              AST RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		CONDICION c = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new IF(c, s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // sentencia ::= IF AP condicion CP sentencia ELSE sentencia 
            {
              AST RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		CONDICION c = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int s1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int s1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		AST s1 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int s2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int s2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s2 = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                                                            IF p1 = new IF(c, s1); 
                                                            RESULT = new IFELSE(p1, s2); 
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // sentencia ::= WHILE AP condicion CP sentencia 
            {
              AST RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		CONDICION c = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new WHILE(c,s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // sentencia ::= DO sentencia WHILE AP condicion CP PYC 
            {
              AST RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		CONDICION c = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 
                                                            RESULT = new DOWHILE(s, c); 
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // sentencia ::= FOR AP expresion PYC condicion PYC expresion CP sentencia 
            {
              AST RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		CONDICION c = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e2 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		AST s = (AST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                                                            AST sentwhile = new AST(s, e2);
                                                            WHILE eqFor = new WHILE(c, sentwhile);
                                                            RESULT = new FOR(e1, eqFor);
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // declarVariable ::= tipo IDENT 
            {
              DECLARVAR RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		TIPO t = (TIPO)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                                                            if(TablaSimbolos.estaDefinida(id)){
                                                                Generador.error();
                                                            } else {
                                                                // COMENTARIO System.out.println("variable ind "+id+" acaba de declararse");
                                                                TablaSimbolos.insertar(t, id);
                                                            }
                                                            RESULT = new DECLARVAR(t, id);
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declarVariable",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // declarVariable ::= tipo IDENT IGUAL expresion 
            {
              DECLARVAR RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		TIPO t = (TIPO)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  
                                                            ASIG dcha = new ASIG(id, e);
                                                            if(TablaSimbolos.estaDefinida(id)){
                                                                Generador.error();
                                                            }
                                                            if (t.getTipo()!=e.getTipo()){
                                                                Generador.error();
                                                            }
                                                            TablaSimbolos.insertar(t, id);
                                                            // COMENTARIO System.out.println("variable ind "+id+" acaba de declararse");
                                                            RESULT = new DECLARVAR(null, t, id, dcha);
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declarVariable",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // declarVariable ::= declarVariable COMA IDENT IGUAL expresion 
            {
              DECLARVAR RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		DECLARVAR d = (DECLARVAR)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                                                            ASIG dcha = new ASIG(id, e);
                                                            if(TablaSimbolos.estaDefinida(id)){
                                                                Generador.error();
                                                            }
                                                            if (d.getTipo().getTipo()!=e.getTipo()){
                                                                Generador.error();
                                                            }
                                                            TablaSimbolos.insertar(d.getTipo(), id);
                                                            // COMENTARIO System.out.println("variable ind "+id+" acaba de declararse");
                                                            RESULT = new DECLARVAR(d, d.getTipo(), id, dcha);    
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declarVariable",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // declarVariable ::= declarVariable COMA IDENT 
            {
              DECLARVAR RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		DECLARVAR d = (DECLARVAR)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                                                            if(TablaSimbolos.estaDefinida(id)){
                                                                Generador.error();
                                                            } else {
                                                                // COMENTARIO System.out.println("variable lst "+id+" acaba de declararse");
                                                                TablaSimbolos.insertar(d.getTipo(), id);
                                                            }
                                                            RESULT = new DECLARVAR(d.getTipo(), id);
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declarVariable",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // declarVector ::= tipo IDENT AC ENTERO CC 
            {
              DECLARVEC RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		TIPO t = (TIPO)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
                                                            if(TablaSimbolos.estaDefinida(id)){
                                                                Generador.error();
                                                            }
                                                            int tt = TIPO.VECTOR;
                                                            int st = t.getTipo();
                                                            int tam = Integer.valueOf(n);
                                                            TIPO tipo = new TIPO(tt, st, tam);
                                                            TablaSimbolos.insertar(tipo, id);
                                                            RESULT = new DECLARVEC(tipo, id);
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declarVector",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // declarVector ::= tipo IDENT AC ENTERO CC IGUAL expvector 
            {
              DECLARVEC RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		TIPO t = (TIPO)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		VECTOR v = (VECTOR)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                                                            if(TablaSimbolos.estaDefinida(id)){
                                                                Generador.error();
                                                            }
                                                            int tt = TIPO.VECTOR;
                                                            int st = t.getTipo();
                                                            int tam = Integer.valueOf(n);
                                                            if(st != v.getSubtipo()){
                                                                Generador.error();
                                                            }
                                                            if(tam < v.getTam()){
                                                                Generador.error();
                                                            }
                                                            TIPO tipo = new TIPO(tt,st,tam);
                                                            TablaSimbolos.insertar(tipo, id);
                                                            ASIG dcha = new ASIG(id, v);
                                                            RESULT = new DECLARVEC(null, tipo, id, dcha);
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declarVector",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // declarVector ::= declarVector COMA IDENT AC ENTERO CC 
            {
              DECLARVEC RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		DECLARVEC d = (DECLARVEC)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
                                                            if(TablaSimbolos.estaDefinida(id)){
                                                                Generador.error();
                                                            }
                                                            int tt = TIPO.VECTOR;
                                                            int st = d.getTipo().getTipo();
                                                            int tam = Integer.valueOf(n);
                                                            TIPO tipo = new TIPO(tt, st, tam);
                                                            TablaSimbolos.insertar(tipo, id);
                                                            RESULT = new DECLARVEC(d, tipo, id, null);
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declarVector",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // declarVector ::= declarVector COMA IDENT AC ENTERO CC IGUAL expvector 
            {
              DECLARVEC RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		DECLARVEC d = (DECLARVEC)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		VECTOR v = (VECTOR)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                                                            if(TablaSimbolos.estaDefinida(id)){
                                                                Generador.error();
                                                            }
                                                            int tt = TIPO.VECTOR;
                                                            int st = d.getTipo().getTipo();
                                                            int tam = Integer.valueOf(n);
                                                            if(st != v.getSubtipo()){
                                                                Generador.error();
                                                            }
                                                            if(tam < v.getTam()){
                                                                Generador.error();
                                                            }
                                                            TIPO tipo = new TIPO(tt,st,tam);
                                                            TablaSimbolos.insertar(tipo, id);
                                                            ASIG dcha = new ASIG(id, v);
                                                            RESULT = new DECLARVEC(d, tipo, id, dcha);
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declarVector",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // tipo ::= INT 
            {
              TIPO RESULT =null;
		 RESULT = new TIPO(TIPO.ENTERO); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // tipo ::= FLOAT 
            {
              TIPO RESULT =null;
		 RESULT = new TIPO(TIPO.REAL); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // tipo ::= CHAR 
            {
              TIPO RESULT =null;
		 RESULT = new TIPO(TIPO.CARACTER); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // tipo ::= STRING 
            {
              TIPO RESULT =null;
		 RESULT = new TIPO(TIPO.CADENA); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // tipo ::= tipo AC CC 
            {
              TIPO RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		TIPO t = (TIPO)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new TIPO(TIPO.VECTOR, t.getTipo(), 0); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expresion ::= expresion MAS expresion 
            {
              EXPRESION RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e2 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new MAS(e1, e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expresion ::= expresion MENOS expresion 
            {
              EXPRESION RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e2 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new MENOS(e1, e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expresion ::= expresion POR expresion 
            {
              EXPRESION RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e2 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new POR(e1, e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expresion ::= expresion DIV expresion 
            {
              EXPRESION RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e2 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DIV(e1, e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expresion ::= MENOS expresion 
            {
              EXPRESION RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new MENOS(null, e); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expresion ::= AP expresion CP 
            {
              EXPRESION RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		EXPRESION e = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expresion ::= ENTERO 
            {
              EXPRESION RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CTE(n, null, new TIPO(TIPO.ENTERO)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expresion ::= REAL 
            {
              EXPRESION RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String r = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CTE(r, null, new TIPO(TIPO.REAL)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expresion ::= CADENA 
            {
              EXPRESION RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CADENA(s, new TIPO(TIPO.CADENA)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expresion ::= CARACTER 
            {
              EXPRESION RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CTE(c, null, new TIPO(TIPO.CARACTER)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expresion ::= IDENT 
            {
              EXPRESION RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                                                            TIPO tipo = TablaSimbolos.getTipo(id);
                                                            //Si no ha sido aun declarada emitimos error
                                                            if(tipo==null){
                                                                // COMENTARIO System.out.println("El tipo de la variable "+id+" es nulo");
                                                                Generador.error();
                                                            }
                                                            RESULT = new CTE(id, null, tipo); 
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expresion ::= IDENT IGUAL expresion 
            {
              EXPRESION RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  
                                                            TIPO tipo = TablaSimbolos.getTipo(id);
                                                            //Si no ha sido declarada emitimos error
                                                            if(tipo == null){
                                                                // COMENTARIO System.out.println("El tipo de la variable "+id+" es nulo (id = e)");
                                                                Generador.error();
                                                            }
                                                            //Si es declarada pero se le asigna un tipo correcto
                                                            //emitimos error
                                                            // COMENTARIO System.out.println("El tipo de la variable "+id+" es "+tipo.getTipo() );
                                                            // COMENTARIO System.out.println("El tipo de la expresion es "+" "+e.getTipo());
                                                            if(tipo.getTipo() != e.getTipo()){  
                                                                Generador.error();
                                                            }
                                                            RESULT = new ASIG(id, e); 
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expresion ::= IDENT AC expresion CC 
            {
              EXPRESION RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		EXPRESION e = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		  
                                                            if(!TablaSimbolos.estaDefinida(id)){
                                                                Generador.error();
                                                            }
                                                            RESULT = new ELEMVECTOR(id, e, null);
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expresion ::= IDENT AC expresion CC IGUAL expresion 
            {
              EXPRESION RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e2 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                                                            if(!TablaSimbolos.estaDefinida(id)){
                                                                Generador.error();
                                                            }
                                                            RESULT = new ELEMVECTOR(id, e1, e2);
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expresion ::= IDENT IGUAL expvector 
            {
              EXPRESION RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		VECTOR e = (VECTOR)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                                                            if(!TablaSimbolos.estaDefinida(id)){
                                                                Generador.error();
                                                            }
                                                            TIPO tipo = TablaSimbolos.getTipo(id);
                                                            if(tipo.getTipo()!=e.getTipo()){
                                                                Generador.error();
                                                            }
                                                            RESULT = new ASIG(id, e);
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expresion ::= 
            {
              EXPRESION RESULT =null;
		 
                                                           //Se añade para el bucle for con expresiones vacias
                                                           RESULT = new EXPRESION(null, null); 
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expvector ::= ALL listaElems CLL 
            {
              VECTOR RESULT =null;
		int leleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int leright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		VECTOR le = (VECTOR)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = le; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expvector",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // listaElems ::= listaElems COMA expresion 
            {
              VECTOR RESULT =null;
		int leleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int leright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		VECTOR le = (VECTOR)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
                                                            le.anyadir(e);
                                                            RESULT = le;
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaElems",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // listaElems ::= expresion 
            {
              VECTOR RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                                                            RESULT = new VECTOR();
                                                            RESULT.anyadir(e);
                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaElems",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // condicion ::= expresion IGUALDAD expresion 
            {
              CONDICION RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e2 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new IGUALDAD(e1,e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // condicion ::= expresion NOIGUALDAD expresion 
            {
              CONDICION RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new NOIGUALDAD(e1,e); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // condicion ::= expresion MENOR expresion 
            {
              CONDICION RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e2 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new MENOR(e1,e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // condicion ::= expresion MENOREQ expresion 
            {
              CONDICION RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new MENOREQ(e1,e); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // condicion ::= expresion MAYOR expresion 
            {
              CONDICION RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e2 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new MAYOR(e1,e2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // condicion ::= expresion MAYOREQ expresion 
            {
              CONDICION RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		EXPRESION e1 = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		EXPRESION e = (EXPRESION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new MAYOREQ(e1,e); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // condicion ::= NOT condicion 
            {
              CONDICION RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		CONDICION c = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new NOT(c,null); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // condicion ::= condicion AND condicion 
            {
              CONDICION RESULT =null;
		int c1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int c1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		CONDICION c1 = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int c2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int c2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		CONDICION c2 = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AND(c1, c2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // condicion ::= condicion OR condicion 
            {
              CONDICION RESULT =null;
		int c1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int c1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		CONDICION c1 = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int c2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int c2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		CONDICION c2 = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new OR(c1,c2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // condicion ::= AP condicion CP 
            {
              CONDICION RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		CONDICION c = (CONDICION)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = c; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicion",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
