
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOREQ = 21;
  public static final int AC = 12;
  public static final int CHAR = 35;
  public static final int POR = 4;
  public static final int ENTERO = 38;
  public static final int INT = 33;
  public static final int NOIGUALDAD = 20;
  public static final int FOR = 31;
  public static final int CP = 9;
  public static final int NOT = 25;
  public static final int AND = 23;
  public static final int IGUAL = 7;
  public static final int CARACTER = 41;
  public static final int IGUALDAD = 19;
  public static final int OR = 24;
  public static final int DIV = 5;
  public static final int CC = 13;
  public static final int IF = 27;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 14;
  public static final int CADENA = 40;
  public static final int MENOS = 3;
  public static final int MENOR = 18;
  public static final int IDENT = 37;
  public static final int MENOSUNARIO = 6;
  public static final int CLL = 11;
  public static final int REAL = 39;
  public static final int MAYOR = 17;
  public static final int ELSE = 30;
  public static final int PUNTO = 15;
  public static final int WHILE = 29;
  public static final int FLOAT = 34;
  public static final int STRING = 36;
  public static final int ALL = 10;
  public static final int MAYOREQ = 22;
  public static final int AP = 8;
  public static final int PRINT = 26;
  public static final int LENGTH = 32;
  public static final int DO = 28;
  public static final int PYC = 16;
  public static final int MAS = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "MENOSUNARIO",
  "IGUAL",
  "AP",
  "CP",
  "ALL",
  "CLL",
  "AC",
  "CC",
  "COMA",
  "PUNTO",
  "PYC",
  "MAYOR",
  "MENOR",
  "IGUALDAD",
  "NOIGUALDAD",
  "MENOREQ",
  "MAYOREQ",
  "AND",
  "OR",
  "NOT",
  "PRINT",
  "IF",
  "DO",
  "WHILE",
  "ELSE",
  "FOR",
  "LENGTH",
  "INT",
  "FLOAT",
  "CHAR",
  "STRING",
  "IDENT",
  "ENTERO",
  "REAL",
  "CADENA",
  "CARACTER"
  };
}

